# Generated by Django 4.2.1 on 2023-06-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mobile',
            new_name='number',
        ),
    ]
