# Generated by Django 4.2.1 on 2023-06-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_profile_id_user_alter_profile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.CharField(max_length=10, verbose_name=''),
        ),
    ]
