# Generated by Django 4.2.1 on 2023-06-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='privacy',
            field=models.CharField(default='public', max_length=10),
        ),
    ]
