# Generated by Django 4.2.1 on 2023-06-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_post_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='privacy',
            field=models.CharField(default='public', max_length=20),
        ),
    ]
